//---------------------------------------------------------------------------

#ifndef PrincipalH
#define PrincipalH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <MPlayer.hpp>
#include <Graphics.hpp>
//---------------------------------------------------------------------------
class TfrmPrincipal : public TForm
{
__published:	// IDE-managed Components
        TTimer *tmrStarting;
        TTimer *tmrLeitura;
        TTimer *ConexaoWatch;
        TTimer *tmrReconecta;
        TTimer *Lista;
        TTimer *tmrPartida;
        TTimer *tmrParada;
        TTimer *tmrDemandaNTP;
        TMediaPlayer *mplAudio;
        TTimer *tmrAbrirVOD116;
        TTimer *tmrFecharVOD116;
        TPanel *Panel1;
        TLabel *Label67;
        TLabel *lblNTP;
        TLabel *Label69;
        TLabel *lblPLA;
        TLabel *Label71;
        TLabel *lblNGG;
        TShape *shpEmRemoto;
        TLabel *Label33;
        TShape *shpEmLocal;
        TLabel *Label34;
        TShape *shpBatOver1Ativo;
        TLabel *Label61;
        TShape *shpBatOver1EmLoc;
        TLabel *Label62;
        TShape *shpBatOver1EmRem;
        TLabel *Label63;
        TShape *shpBatOver2Ativo;
        TLabel *Label64;
        TShape *shpBatOver2EmLoc;
        TLabel *Label65;
        TShape *shpBatOver2EmRem;
        TLabel *Label66;
        TButton *btnRearmar;
        TButton *btnSilenciar;
        TLabel *lblContaPartida;
        TLabel *lblContaParada;
        TLabel *Label35;
        TLabel *Label36;
        TShape *shpPartidaNormalSel;
        TShape *shpPartidaRapidaSel;
        TLabel *Label44;
        TLabel *Label45;
        TButton *Button1;
        TPanel *pnlLocal;
        TShape *shpInibiPartida;
        TShape *shpInibiParada;
        TButton *btnInibirPartida;
        TButton *btnInibirParada;
        TButton *btnCaturrar;
        TEdit *txtCaturrar;
        TLabel *Label43;
        TShape *shpMotLenta;
        TShape *shpMotRapida;
        TShape *shpBatOver1EmLocEx;
        TShape *shpBatOver2EmLocEx;
        TLabel *Label68;
        TLabel *lblDemandaLocal;
        TButton *btnPartirLocal;
        TButton *btnPararLocal;
        TButton *btnPartirRLocal;
        TButton *btnLowCrank;
        TButton *btnHighCrank;
        TButton *btnBatOver1Loc;
        TButton *btnBatOver2Loc;
        TButton *btnAclNTP;
        TButton *btnDaclNTP;
        TEdit *txtSETNTP;
        TButton *btnSETNTP;
        TButton *btnPararEmergLoc;
        TShape *Shape1;
        TButton *btnEmRemLoc;
        TLabel *lblSPNTPEHT1;
        TLabel *Label52;
        TLabel *Label54;
        TLabel *lblSPNTPEHT2;
        TLabel *Label53;
        TLabel *lblSPPLAEHT1;
        TLabel *Label56;
        TLabel *Label57;
        TLabel *lblSPPLAEHT2;
        TLabel *Label60;
        TShape *shpModoPLA;
        TLabel *Label70;
        TLabel *Label73;
        TShape *shpModoNTP;
        TShape *shpQQTRIP;
        TLabel *Label72;
        TShape *shpQQALARME;
        TLabel *Label74;
        TLabel *Label75;
        TShape *shpVVEXTODFECH;
        TPanel *pnlStatus;
        TImage *Image1;
        TShape *Shape6;
        TLabel *lblLista;
        TLabel *lblBufferEx;
        TLabel *lblTamListaIDs;
        TLabel *lblInicioPrograma;
        TLabel *lblBufferR;
        TLabel *lblBufferW;
        TLabel *lblProgramaAtual;
        TLabel *lblQuedas;
        TLabel *Label58;
        TLabel *lblWatchdogEx;
        TLabel *lblWatchdog;
        TLabel *lblEndereco;
        TGroupBox *grbIPQM;
        TImage *imgGSD;
        TLabel *lblIPQM;
        TLabel *lblGSD;
        TLabel *lbl142;
        TImage *imgIPQM;
        TGroupBox *grbNAVIO;
        TImage *imgNAVIO;
        TLabel *lblNAVIO;
        TLabel *Label123;
        TLabel *Label124;
        TLabel *Label125;
        TLabel *Label82;
        TPanel *shpAguarde;
        TLabel *lblAguarde;
        TButton *btnReset;
        TPanel *pnlComandos;
        TShape *Shape10;
        TShape *Shape22;
        TShape *Shape7;
        TShape *Shape23;
        TShape *Shape18;
        TShape *Shape17;
        TShape *Shape16;
        TShape *Shape15;
        TShape *Shape14;
        TShape *Shape12;
        TShape *Shape11;
        TShape *Shape9;
        TShape *Shape21;
        TShape *Shape20;
        TShape *Shape19;
        TShape *Shape8;
        TShape *shpPartirNormalETH1;
        TShape *shpPartirNormalETH2;
        TLabel *lblComandos;
        TLabel *Label11;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label7;
        TLabel *Label8;
        TShape *shpPararETH1;
        TShape *shpPararETH2;
        TLabel *Label9;
        TShape *shpPararEmergETH1;
        TShape *shpPararEmergETH2;
        TShape *shpPararEmergHDW;
        TLabel *Label10;
        TShape *shpBatOver1ETH1;
        TShape *shpBatOver1ETH2;
        TShape *shpBatOver1HDW;
        TLabel *Label12;
        TShape *shpBatOver2ETH1;
        TShape *shpBatOver2ETH2;
        TShape *shpBatOver2HDW;
        TLabel *Label13;
        TLabel *Label1;
        TLabel *Label2;
        TShape *shpPararIncendioETH1;
        TShape *shpPararIncendioETH2;
        TShape *shpPararIncendioHDW;
        TLabel *Label3;
        TShape *shpPartirRapidoETH1;
        TShape *shpPartirRapidoETH2;
        TLabel *Label4;
        TLabel *Label14;
        TLabel *Label15;
        TLabel *Label16;
        TLabel *Label17;
        TLabel *Label18;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label21;
        TShape *shpReconhecerETH1;
        TShape *shpReconhecerETH2;
        TShape *shpSilenciarETH1;
        TShape *shpSilenciarETH2;
        TShape *Shape4;
        TShape *shpDBatOver1ETH1;
        TShape *shpDBatOver1ETH2;
        TShape *shpDBatOver1HDW;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label55;
        TLabel *Label59;
        TShape *shpDBatOver2ETH1;
        TShape *shpDBatOver2ETH2;
        TShape *shpDBatOver2HDW;
        TShape *ACK01;
        TShape *ACK02;
        TShape *ACK03;
        TShape *ACK04;
        TShape *ACK05;
        TShape *shpAbrirVOD116ETH1;
        TShape *shpAbrirVOD116ETH2;
        TLabel *Label76;
        TLabel *Label77;
        TShape *shpFecharVOD116ETH1;
        TShape *shpFecharVOD116ETH2;
        TLabel *Label78;
        TLabel *Label79;
        TShape *ACK06;
        TShape *ACK07;
        TShape *Shape5;
        TShape *ACK08;
        TShape *shpAtivarModoPLA;
        TLabel *Label80;
        TLabel *Label81;
        TButton *btnResetAck;
        TShape *Shape13;
        TShape *Shape24;
        TShape *Shape25;
        TLabel *Label83;
        TLabel *Label84;
        TLabel *Label85;
        TPanel *pnlFunc;
        TShape *Shape2;
        TLabel *Label41;
        TShape *shpOKPARTIRCRANK;
        TLabel *Label22;
        TLabel *Label23;
        TShape *shpATIVANDOAUXIL;
        TLabel *Label24;
        TShape *shpACELPRAQUEIMA;
        TLabel *Label25;
        TShape *shpAPLICANDOOD;
        TShape *shpACELPRARALANTI;
        TLabel *Label26;
        TShape *shpAQCTGEMRALANTI;
        TLabel *Label27;
        TShape *shpEMOPERACAO;
        TLabel *Label28;
        TShape *shpRESFEMRALANTI;
        TLabel *Label29;
        TShape *shpEMCOASTDOWN;
        TLabel *Label30;
        TShape *shpPARADA;
        TLabel *Label31;
        TShape *shpOKPARACRANK;
        TLabel *Label32;
        TShape *shpNaoParadaHDW;
        TLabel *Label37;
        TShape *shpPartindoAcesaHDW;
        TLabel *Label38;
        TShape *shpEmOperacaoHDW;
        TLabel *Label39;
        TShape *shpParandoHDW;
        TLabel *Label40;
        TLabel *Label42;
        TShape *shpLOWCRANK;
        TLabel *Label46;
        TShape *shpPURGAMOTLENTA;
        TLabel *Label47;
        TShape *shpFORADESERVICO;
        TLabel *Label48;
        TLabel *Label49;
        TShape *shpHIGHCRANK;
        TButton *btnFechar;
        TButton *btnStatus;
        TImage *Image2;
        TButton *btncmdlocal;
        TButton *btnCtrl;
        TButton *btncmdremotos;
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall ConexaoWatchTimer(TObject *Sender);
        void __fastcall tmrStartingTimer(TObject *Sender);
        void __fastcall ListaTimer(TObject *Sender);
        void __fastcall tmrReconectaTimer(TObject *Sender);
        void __fastcall tmrLeituraTimer(TObject *Sender);
        void __fastcall tmrPartidaTimer(TObject *Sender);
        void __fastcall btnEmRemLocClick(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall tmrParadaTimer(TObject *Sender);
        void __fastcall btnPartirLocalClick(TObject *Sender);
        void __fastcall btnPararLocalClick(TObject *Sender);
        void __fastcall btnPartirRLocalClick(TObject *Sender);
        void __fastcall Button1Click(TObject *Sender);
        void __fastcall btnInibirPartidaClick(TObject *Sender);
        void __fastcall btnInibirParadaClick(TObject *Sender);
        void __fastcall btnLowCrankClick(TObject *Sender);
        void __fastcall btnHighCrankClick(TObject *Sender);
        void __fastcall btnBatOver1LocClick(TObject *Sender);
        void __fastcall btnBatOver2LocClick(TObject *Sender);
        void __fastcall tmrDemandaNTPTimer(TObject *Sender);
        void __fastcall btnAclNTPClick(TObject *Sender);
        void __fastcall btnDaclNTPClick(TObject *Sender);
        void __fastcall btnSETNTPClick(TObject *Sender);
        void __fastcall btnRearmarClick(TObject *Sender);
        void __fastcall btnPararEmergLocClick(TObject *Sender);
        void __fastcall btnSilenciarClick(TObject *Sender);
        void __fastcall btnResetAckClick(TObject *Sender);
        void __fastcall tmrAbrirVOD116Timer(TObject *Sender);
        void __fastcall tmrFecharVOD116Timer(TObject *Sender);
        void __fastcall btnCaturrarClick(TObject *Sender);
        void __fastcall btnStatusClick(TObject *Sender);
        void __fastcall btncmdlocalClick(TObject *Sender);
        void __fastcall btnCtrlClick(TObject *Sender);
        void __fastcall btncmdremotosClick(TObject *Sender);
        void __fastcall btnFecharClick(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TfrmPrincipal(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TfrmPrincipal *frmPrincipal;
//---------------------------------------------------------------------------
#endif
