//---------------------------------------------------------------------------

#ifndef MancaisH
#define MancaisH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ComCtrls.hpp>
#include <ExtCtrls.hpp>
//---------------------------------------------------------------------------
class TfrmMancal : public TForm
{
__published:	// IDE-managed Components
        TPanel *pnlMODSBB;
        TShape *Shape1;
        TLabel *Label5;
        TLabel *lblMODSBB_TEMPMANCAL1;
        TLabel *lblInit2;
        TLabel *Label8;
        TLabel *lblMODSBB_TEMPMANCAL3;
        TLabel *Label10;
        TLabel *lblMODSBB_TEMPMANCAL5;
        TLabel *Label12;
        TLabel *lblMODSBB_TEMPMANCAL7;
        TLabel *Label15;
        TLabel *lblMODSBB_TEMPMANCAL2;
        TLabel *Label17;
        TLabel *lblMODSBB_TEMPMANCAL4;
        TLabel *Label20;
        TLabel *lblMODSBB_TEMPMANCAL6;
        TLabel *Label37;
        TLabel *lblMODSBB_TEMPMANCAL8;
        TProgressBar *prbMODSBB_TEMPMANCAL1;
        TEdit *txtMODSBB_TEMPMANCAL1;
        TButton *btnMODSBB_TEMPMANCAL1;
        TProgressBar *prbMODSBB_TEMPMANCAL3;
        TEdit *txtMODSBB_TEMPMANCAL3;
        TButton *btnMODSBB_TEMPMANCAL3;
        TProgressBar *prbMODSBB_TEMPMANCAL5;
        TEdit *txtMODSBB_TEMPMANCAL5;
        TButton *btnMODSBB_TEMPMANCAL5;
        TProgressBar *prbMODSBB_TEMPMANCAL7;
        TEdit *txtMODSBB_TEMPMANCAL7;
        TButton *btnMODSBB_TEMPMANCAL7;
        TProgressBar *prbMODSBB_TEMPMANCAL2;
        TEdit *txtMODSBB_TEMPMANCAL2;
        TButton *btnMODSBB_TEMPMANCAL2;
        TProgressBar *prbMODSBB_TEMPMANCAL4;
        TEdit *txtMODSBB_TEMPMANCAL4;
        TButton *btnMODSBB_TEMPMANCAL4;
        TProgressBar *prbMODSBB_TEMPMANCAL6;
        TEdit *txtMODSBB_TEMPMANCAL6;
        TButton *btnMODSBB_TEMPMANCAL6;
        TProgressBar *prbMODSBB_TEMPMANCAL8;
        TEdit *txtMODSBB_TEMPMANCAL8;
        TButton *btnMODSBB_TEMPMANCAL8;
        TPanel *pnlMODSBE;
        TShape *Shape2;
        TLabel *Label39;
        TLabel *lblMODSBE_TEMPMANCAL1;
        TLabel *lblInit3;
        TLabel *Label42;
        TLabel *lblMODSBE_TEMPMANCAL3;
        TLabel *Label44;
        TLabel *lblMODSBE_TEMPMANCAL5;
        TLabel *Label46;
        TLabel *lblMODSBE_TEMPMANCAL7;
        TLabel *Label48;
        TLabel *lblMODSBE_TEMPMANCAL2;
        TLabel *Label50;
        TLabel *lblMODSBE_TEMPMANCAL4;
        TLabel *Label52;
        TLabel *lblMODSBE_TEMPMANCAL6;
        TLabel *Label54;
        TLabel *lblMODSBE_TEMPMANCAL8;
        TProgressBar *prbMODSBE_TEMPMANCAL1;
        TEdit *txtMODSBE_TEMPMANCAL1;
        TButton *btnMODSBE_TEMPMANCAL1;
        TProgressBar *prbMODSBE_TEMPMANCAL3;
        TEdit *txtMODSBE_TEMPMANCAL3;
        TButton *btnMODSBE_TEMPMANCAL3;
        TProgressBar *prbMODSBE_TEMPMANCAL5;
        TEdit *txtMODSBE_TEMPMANCAL5;
        TButton *btnMODSBE_TEMPMANCAL5;
        TProgressBar *prbMODSBE_TEMPMANCAL7;
        TEdit *txtMODSBE_TEMPMANCAL7;
        TButton *btnMODSBE_TEMPMANCAL7;
        TProgressBar *prbMODSBE_TEMPMANCAL2;
        TEdit *txtMODSBE_TEMPMANCAL2;
        TButton *btnMODSBE_TEMPMANCAL2;
        TProgressBar *prbMODSBE_TEMPMANCAL4;
        TEdit *txtMODSBE_TEMPMANCAL4;
        TButton *btnMODSBE_TEMPMANCAL4;
        TProgressBar *prbMODSBE_TEMPMANCAL6;
        TEdit *txtMODSBE_TEMPMANCAL6;
        TButton *btnMODSBE_TEMPMANCAL6;
        TProgressBar *prbMODSBE_TEMPMANCAL8;
        TEdit *txtMODSBE_TEMPMANCAL8;
        TButton *btnMODSBE_TEMPMANCAL8;
        TPanel *pnlMODPRI;
        TShape *Shape3;
        TLabel *Label14;
        TLabel *lblMODPRI_TEMPMANCAL1;
        TLabel *lblInit1;
        TLabel *Label22;
        TLabel *lblMODPRI_TEMPMANCAL3;
        TLabel *Label24;
        TLabel *lblMODPRI_TEMPMANCAL5;
        TLabel *Label26;
        TLabel *lblMODPRI_TEMPMANCAL7;
        TLabel *Label29;
        TLabel *lblMODPRI_TEMPMANCAL2;
        TLabel *Label31;
        TLabel *lblMODPRI_TEMPMANCAL4;
        TLabel *Label33;
        TLabel *lblMODPRI_TEMPMANCAL6;
        TLabel *Label35;
        TLabel *lblMODPRI_TEMPMANCAL8;
        TLabel *Label1;
        TLabel *lblMODPRI_TEMPMANCAL9;
        TLabel *Label3;
        TLabel *lblMODPRI_TEMPMANCAL10;
        TProgressBar *prbMODPRI_TEMPMANCAL1;
        TEdit *txtMODPRI_TEMPMANCAL1;
        TButton *btnMODPRI_TEMPMANCAL1;
        TProgressBar *prbMODPRI_TEMPMANCAL3;
        TEdit *txtMODPRI_TEMPMANCAL3;
        TButton *btnMODPRI_TEMPMANCAL3;
        TProgressBar *prbMODPRI_TEMPMANCAL5;
        TEdit *txtMODPRI_TEMPMANCAL5;
        TButton *btnMODPRI_TEMPMANCAL5;
        TProgressBar *prbMODPRI_TEMPMANCAL7;
        TEdit *txtMODPRI_TEMPMANCAL7;
        TButton *btnMODPRI_TEMPMANCAL7;
        TProgressBar *prbMODPRI_TEMPMANCAL2;
        TEdit *txtMODPRI_TEMPMANCAL2;
        TButton *btnMODPRI_TEMPMANCAL2;
        TProgressBar *prbMODPRI_TEMPMANCAL4;
        TEdit *txtMODPRI_TEMPMANCAL4;
        TButton *btnMODPRI_TEMPMANCAL4;
        TProgressBar *prbMODPRI_TEMPMANCAL6;
        TEdit *txtMODPRI_TEMPMANCAL6;
        TButton *btnMODPRI_TEMPMANCAL6;
        TProgressBar *prbMODPRI_TEMPMANCAL8;
        TEdit *txtMODPRI_TEMPMANCAL8;
        TButton *btnMODPRI_TEMPMANCAL8;
        TProgressBar *prbMODPRI_TEMPMANCAL9;
        TEdit *txtMODPRI_TEMPMANCAL9;
        TButton *btnMODPRI_TEMPMANCAL9;
        TProgressBar *prbMODPRI_TEMPMANCAL10;
        TEdit *txtMODPRI_TEMPMANCAL10;
        TButton *btnMODPRI_TEMPMANCAL10;
        TPanel *pnlEixos;
        TShape *Shape4;
        TLabel *lblInit4;
        TLabel *Label4;
        TLabel *lblBB_MLEAV_TEMP;
        TLabel *Label7;
        TLabel *lblBB_MLEAR_TEMP;
        TProgressBar *prbBB_MLEAV_TEMP;
        TEdit *txtBB_MLEAV_TEMP;
        TButton *btnBB_MLEAV_TEMP;
        TProgressBar *prbBB_MLEAR_TEMP;
        TEdit *txtBB_MLEAR_TEMP;
        TButton *btnBB_MLEAR_TEMP;
        TShape *Shape5;
        TLabel *lblInit5;
        TLabel *Label13;
        TLabel *lblBE_MLEAV_TEMP;
        TLabel *Label18;
        TLabel *lblBE_MLEAR_TEMP;
        TProgressBar *prbBE_MLEAV_TEMP;
        TEdit *txtBE_MLEAV_TEMP;
        TButton *btnBE_MLEAV_TEMP;
        TProgressBar *prbBE_MLEAR_TEMP;
        TEdit *txtBE_MLEAR_TEMP;
        TButton *btnBE_MLEAR_TEMP;
        TButton *btnMODSBB;
        TButton *btnMODPRI;
        TButton *btnEIXOS;
        TButton *btnMODSBE;
        TButton *btnFechar;
        void __fastcall btnMODSBB_TEMPMANCAL1Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL2Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL3Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL4Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL5Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL6Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL7Click(TObject *Sender);
        void __fastcall btnMODSBB_TEMPMANCAL8Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL1Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL2Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL3Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL4Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL5Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL6Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL7Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL8Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL9Click(TObject *Sender);
        void __fastcall btnMODPRI_TEMPMANCAL10Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL1Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL2Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL3Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL4Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL5Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL6Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL7Click(TObject *Sender);
        void __fastcall btnMODSBE_TEMPMANCAL8Click(TObject *Sender);
        void __fastcall btnBB_MLEAV_TEMPClick(TObject *Sender);
        void __fastcall btnBB_MLEAR_TEMPClick(TObject *Sender);
        void __fastcall btnBE_MLEAV_TEMPClick(TObject *Sender);
        void __fastcall btnBE_MLEAR_TEMPClick(TObject *Sender);
        void __fastcall btnMODSBBClick(TObject *Sender);
        void __fastcall btnMODPRIClick(TObject *Sender);
        void __fastcall btnEIXOSClick(TObject *Sender);
        void __fastcall btnMODSBEClick(TObject *Sender);
        void __fastcall btnFecharClick(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TfrmMancal(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TfrmMancal *frmMancal;
//---------------------------------------------------------------------------
#endif
