//---------------------------------------------------------------------------

#ifndef PrincipalH
#define PrincipalH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <ComCtrls.hpp>
#include <Menus.hpp>
#include <Graphics.hpp>

//---------------------------------------------------------------------------
class TfrmPrincipal : public TForm
{
__published:	// IDE-managed Components
        TTimer *tmrStarting;
        TTimer *tmrLeitura;
        TTimer *ConexaoWatch;
        TTimer *tmrReconecta;
        TTimer *tmrPartir_ERHBC_BBELPN;
        TTimer *tmrParar_ERHBC_BBELPN;
        TMainMenu *mnuMain;
        TMenuItem *mnuMancais;
        TTimer *tmrPressurizar;
        TTimer *tmrDespressurizar;
        TTimer *Lista;
        TPanel *pnlSSSMCP;
        TMenuItem *mnuBBELPN;
        TShape *Shape8;
        TLabel *lblInit9;
        TShape *shpSSSK3_ACPL;
        TLabel *Label35;
        TShape *shpSSSK3_DACPL;
        TLabel *Label36;
        TShape *shpSSSK3_TRAVACPL;
        TLabel *Label39;
        TShape *shpSSSK3_TRAVAR;
        TLabel *Label40;
        TShape *shpSSSK3_NTRAVACPL;
        TLabel *Label41;
        TShape *shpSSSK3_OLPBX;
        TLabel *Label37;
        TShape *Shape9;
        TLabel *lblInit10;
        TShape *shpSSSK4_ACPL;
        TLabel *Label38;
        TShape *shpSSSK4_DACPL;
        TLabel *Label42;
        TShape *shpSSSK4_TRAVACPL;
        TLabel *Label43;
        TShape *shpSSSK4_TRAVAR;
        TLabel *Label44;
        TShape *shpSSSK4_NTRAVACPL;
        TLabel *Label45;
        TShape *shpSSSK4_OLPBX;
        TLabel *Label46;
        TButton *btnSSSK3_ACPL;
        TButton *btnSSSK3_DACPL;
        TButton *btnSSSK3_TRAVACPL;
        TButton *btnSSSK3_NTRAVACPL;
        TButton *btnSSSK3_OLPBX;
        TButton *btnSSSK4_ACPL;
        TButton *btnSSSK4_DACPL;
        TButton *btnSSSK4_TRAVACPL;
        TButton *btnSSSK4_NTRAVACPL;
        TButton *btnSSSK4_OLPBX;
        TButton *btnSSSK3_TRAVAR;
        TButton *btnSSSK4_TRAVAR;
        TPanel *pnlER;
        TShape *Shape5;
        TShape *Shape3;
        TShape *Shape1;
        TLabel *lblInit2;
        TShape *shpMODHID_OLPBX;
        TLabel *Label17;
        TShape *shpMODHID_OLPDIFAL;
        TLabel *Label18;
        TLabel *MODHID_TEMPOL;
        TLabel *lblMODHID_TEMPOL;
        TLabel *MODHID_OLPRESS;
        TLabel *lblMODHID_OLPRESS;
        TShape *Shape2;
        TLabel *lblInit3;
        TShape *shpERPBC_CATRAC;
        TLabel *Label16;
        TShape *Shape4;
        TLabel *lblInit4;
        TShape *shpERPBC_FREIO;
        TLabel *Label20;
        TLabel *lblInit5;
        TLabel *EIXOBBRPM_MODSBB;
        TLabel *lblEIXOBBRPM_MODSBB;
        TLabel *lblInit6;
        TLabel *EIXOBERPM_MODSBE;
        TLabel *lblEIXOBERPM_MODSBE;
        TButton *btnMODHID_OLPBX;
        TButton *btnMODHID_OLPDIFAL;
        TProgressBar *prbMODHID_TEMPOL;
        TButton *btnMODHID_TEMPOL;
        TEdit *txtMODHID_TEMPOL;
        TProgressBar *prbMODHID_OLPRESS;
        TEdit *txtMODHID_OLPRESS;
        TButton *btnMODHID_OLPRESS;
        TButton *btnERPBC_CATRAC;
        TButton *btnERPBC_FREIO;
        TProgressBar *prbEIXOBBRPM_MODSBB;
        TEdit *txtEIXOBBRPM_MODSBB;
        TButton *btnEIXOBBRPM_MODSBB;
        TProgressBar *prbEIXOBERPM_MODSBE;
        TEdit *txtEIXOBERPM_MODSBE;
        TButton *btnEIXOBERPM_MODSBE;
        TMenuItem *mnuER;
        TButton *btnCtrlAutoTemp;
        TPanel *pnlBBELPN;
        TShape *Shape10;
        TLabel *lblInit1;
        TButton *btnMOTELLIG_BBELPN;
        TButton *btnMOTPNLIG_BBELPN;
        TButton *btnEmAut_BBELPN;
        TButton *btnSobrec_BBELPN;
        TButton *btnRemoto_BBELPN;
        TShape *shpLigarBBELPN;
        TLabel *Label8;
        TShape *shpDesligarBBELPN;
        TLabel *Label9;
        TShape *shpAUTOMATICOBBELPN;
        TLabel *Label10;
        TShape *shpMANUALBBELPN;
        TLabel *Label11;
        TShape *shpEmerg_BBELPN;
        TLabel *Label12;
        TShape *shpLibEmerg_BBELPN;
        TLabel *Label13;
        TShape *shpMOTELLIG_BBELPN;
        TShape *shpMOTPNLIG_BBELPN;
        TShape *shpEmAut_BBELPN;
        TShape *shpSobrec_BBELPN;
        TShape *shpRemoto_BBELPN;
        TLabel *Label2;
        TLabel *Label1;
        TLabel *Label15;
        TLabel *Label4;
        TLabel *Label28;
        TButton *btnAUTOHDWSCMLIG_BBELPN;
        TButton *btnAUTOHDWSCMDES_BBELPN;
        TButton *btnPRDEMERGSCMLI_BBELPN;
        TButton *btnPRDEMERGSCMDE_BBELPN;
        TShape *shpAUTOHDWSCMLIG_BBELPN;
        TLabel *Label3;
        TShape *shpAUTOHDWSCMDES_BBELPN;
        TLabel *Label5;
        TShape *shpPRDEMERGSCMLI_BBELPN;
        TLabel *Label6;
        TShape *shpPRDEMERGSCMDE_BBELPN;
        TLabel *Label7;
        TButton *btnPartir;
        TButton *cmdInibirCmd;
        TButton *cmdInibirPress;
        TButton *btnParar;
        TPanel *pnlSSSTG;
        TShape *Shape6;
        TLabel *lblInit7;
        TButton *btnSSSK1_ACPL;
        TButton *btnSSSK1_DACPL;
        TButton *btnSSSK1_TRAVABER;
        TButton *btnSSSK1_NTRAVABER;
        TButton *btnSSSK1_TRAVACPL;
        TButton *btnSSSK1_NTRAVACPL;
        TShape *shpSSSK1_TRAVAR;
        TLabel *Label25;
        TButton *btnSSSK1_TRAVAR;
        TButton *btnSSSK1_FERRAMENTA;
        TShape *shpSSSK1_NTRAVACPL;
        TLabel *Label14;
        TShape *shpSSSK1_TRAVACPL;
        TLabel *Label24;
        TShape *shpSSSK1_NTRAVABER;
        TLabel *Label23;
        TShape *shpSSSK1_TRAVABER;
        TLabel *Label22;
        TShape *shpSSSK1_DACPL;
        TLabel *Label21;
        TShape *shpSSSK1_ACPL;
        TLabel *Label19;
        TLabel *lblInit8;
        TButton *btnSSSK2_ACPL;
        TButton *btnSSSK2_DACPL;
        TButton *btnSSSK2_TRAVABER;
        TButton *btnSSSK2_NTRAVABER;
        TButton *btnSSSK2_TRAVACPL;
        TButton *btnSSSK2_NTRAVACPL;
        TShape *shpSSSK2_TRAVAR;
        TLabel *Label33;
        TButton *btnSSSK2_TRAVAR;
        TButton *btnSSSK2_FERRAMENTA;
        TShape *shpSSSK2_NTRAVACPL;
        TLabel *Label34;
        TShape *shpSSSK2_TRAVACPL;
        TLabel *Label32;
        TShape *shpSSSK2_NTRAVABER;
        TLabel *Label31;
        TLabel *Label30;
        TShape *shpSSSK2_TRAVABER;
        TLabel *Label29;
        TShape *shpSSSK2_ACPL;
        TLabel *Label27;
        TShape *shpSSSK2_DACPL;
        TShape *Shape7;
        TPanel *pnlResumo;
        TShape *Shape16;
        TShape *shpMOTELLIG_BBELPN2;
        TLabel *Label60;
        TShape *shpRemoto_BBELPN2;
        TLabel *Label61;
        TLabel *lblInit11;
        TLabel *lblInit12;
        TShape *shpMODHID_OLPBX2;
        TLabel *Label62;
        TLabel *lblInit13;
        TShape *shpSSSK3_OLPBX2;
        TLabel *Label63;
        TLabel *lblInit14;
        TShape *shpSSSK4_OLPBX2;
        TLabel *Label65;
        TLabel *lblInit15;
        TLabel *lblInit16;
        TLabel *lblEIXOBBRPM_MODSBB2;
        TLabel *Label67;
        TLabel *lblEIXOBERPM_MODSBE2;
        TLabel *Label70;
        TShape *shpSSSK1_ACPL2;
        TLabel *Label64;
        TShape *shpSSSK1_DACPL2;
        TLabel *Label66;
        TShape *shpSSSK1_TRAVABER2;
        TLabel *Label68;
        TShape *shpSSSK1_NTRAVABER2;
        TLabel *Label69;
        TShape *shpSSSK1_TRAVACPL2;
        TLabel *Label71;
        TShape *shpSSSK1_NTRAVACPL2;
        TLabel *Label72;
        TShape *shpSSSK2_ACPL2;
        TLabel *Label73;
        TShape *shpSSSK2_DACPL2;
        TLabel *Label74;
        TShape *shpSSSK2_TRAVABER2;
        TLabel *Label75;
        TShape *shpSSSK2_NTRAVABER2;
        TLabel *Label76;
        TShape *shpSSSK2_TRAVACPL2;
        TLabel *Label77;
        TShape *shpSSSK2_NTRAVACPL2;
        TLabel *Label78;
        TLabel *lblInit17;
        TLabel *lblInit18;
        TLabel *lblInit19;
        TShape *shpSSSK3_ACPL2;
        TLabel *Label82;
        TShape *shpSSSK3_DACPL2;
        TLabel *Label83;
        TShape *shpSSSK3_TRAVACPL2;
        TLabel *Label84;
        TShape *shpSSSK3_NTRAVACPL2;
        TLabel *Label85;
        TLabel *lblInit20;
        TShape *shpSSSK4_ACPL2;
        TLabel *Label87;
        TShape *shpSSSK4_DACPL2;
        TLabel *Label88;
        TShape *shpSSSK4_TRAVACPL2;
        TLabel *Label89;
        TShape *shpSSSK4_NTRAVACPL2;
        TLabel *Label90;
        TPanel *pnlStatus;
        TShape *Shape13;
        TLabel *lblLista;
        TLabel *lblBufferEx;
        TLabel *lblTamListaIDs;
        TLabel *lblInicioPrograma;
        TLabel *lblBufferR;
        TLabel *lblBufferW;
        TLabel *lblProgramaAtual;
        TLabel *lblQuedas;
        TLabel *Label58;
        TLabel *lblWatchdogEx;
        TLabel *lblWatchdog;
        TLabel *lblEndereco;
        TPanel *shpAguarde;
        TLabel *lblAguarde;
        TButton *btnReset;
        TPanel *Panel2;
        TShape *Shape17;
        TShape *Shape14;
        TShape *Shape12;
        TShape *Shape11;
        TShape *shpAFBE_CHEIO;
        TShape *shpAFBB_CHEIO;
        TLabel *Label26;
        TLabel *Label47;
        TLabel *lblMCPBB_RPM;
        TLabel *lblMCPBE_RPM;
        TLabel *lblTGNTP_RPM;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label56;
        TLabel *lblEscorregBB;
        TLabel *lblEscorregBE;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *lblrefMCPBB;
        TLabel *lblrefMCPBE;
        TLabel *lblrefTG;
        TLabel *Label50;
        TLabel *Label59;
        TShape *Shape15;
        TLabel *Label57;
        TLabel *Label79;
        TButton *btnHabilita_Edicao;
        TEdit *txtEscorregBB;
        TEdit *txtEscorregBE;
        TButton *btnEscorreg;
        TButton *btnHabilita_SSS;
        TButton *btnHabilita_Press;
        TMenuItem *mnuStatus;
        TMenuItem *mnuSSSMCP;
        TMenuItem *mnuSSSTG;
        TImage *Image1;
        TButton *btnStatus;
        TButton *btnBBELPN;
        TButton *btnER;
        TButton *btnFechar;
        TButton *btnSSSMCP;
        TButton *btnSSSTG;
        TButton *btnMancais;
        TGroupBox *grbIPQM;
        TImage *imgGSD;
        TLabel *lblIPQM;
        TLabel *lblGSD;
        TLabel *lbl142;
        TImage *imgIPQM;
        TGroupBox *grbNAVIO;
        TImage *imgNAVIO;
        TLabel *lblNAVIO;
        TLabel *Label80;
        TLabel *Label81;
        TLabel *Label86;
        void __fastcall FormCreate(TObject *Sender);
        void __fastcall tmrStartingTimer(TObject *Sender);
        void __fastcall ConexaoWatchTimer(TObject *Sender);
        void __fastcall tmrReconectaTimer(TObject *Sender);
        void __fastcall tmrLeituraTimer(TObject *Sender);
        void __fastcall btnAUTOHDWSCMDES_BBELPNClick(TObject *Sender);
        void __fastcall btnEmAut_BBELPNClick(TObject *Sender);
        void __fastcall btnRemoto_BBELPNClick(TObject *Sender);
        void __fastcall btnAUTOHDWSCMLIG_BBELPNClick(TObject *Sender);
        void __fastcall btnPRDEMERGSCMLI_BBELPNClick(TObject *Sender);
        void __fastcall btnPRDEMERGSCMDE_BBELPNClick(TObject *Sender);
        void __fastcall btnSobrec_BBELPNClick(TObject *Sender);
        void __fastcall btnMOTELLIG_BBELPNClick(TObject *Sender);
        void __fastcall btnMOTPNLIG_BBELPNClick(TObject *Sender);
        void __fastcall tmrPartir_ERHBC_BBELPNTimer(TObject *Sender);
        void __fastcall tmrParar_ERHBC_BBELPNTimer(TObject *Sender);
        void __fastcall btnMODHID_OLPBXClick(TObject *Sender);
        void __fastcall btnMODHID_OLPDIFALClick(TObject *Sender);
        void __fastcall btnMODHID_TEMPOLClick(TObject *Sender);
        void __fastcall btnMODHID_OLPRESSClick(TObject *Sender);
        void __fastcall btnERPBC_CATRACClick(TObject *Sender);
        void __fastcall btnERPBC_FREIOClick(TObject *Sender);
        void __fastcall mnuMancaisClick(TObject *Sender);
        void __fastcall btnEIXOBBRPM_MODSBBClick(TObject *Sender);
        void __fastcall btnEIXOBERPM_MODSBEClick(TObject *Sender);
        void __fastcall btnSSSK1_ACPLClick(TObject *Sender);
        void __fastcall btnSSSK1_DACPLClick(TObject *Sender);
        void __fastcall btnSSSK1_TRAVABERClick(TObject *Sender);
        void __fastcall btnSSSK1_NTRAVABERClick(TObject *Sender);
        void __fastcall btnSSSK1_TRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK1_NTRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK2_ACPLClick(TObject *Sender);
        void __fastcall btnSSSK2_DACPLClick(TObject *Sender);
        void __fastcall btnSSSK2_TRAVABERClick(TObject *Sender);
        void __fastcall btnSSSK2_NTRAVABERClick(TObject *Sender);
        void __fastcall btnSSSK2_TRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK2_NTRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK3_ACPLClick(TObject *Sender);
        void __fastcall btnSSSK3_DACPLClick(TObject *Sender);
        void __fastcall btnSSSK3_TRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK3_NTRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK3_OLPBXClick(TObject *Sender);
        void __fastcall btnSSSK4_ACPLClick(TObject *Sender);
        void __fastcall btnSSSK4_DACPLClick(TObject *Sender);
        void __fastcall btnSSSK4_TRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK4_NTRAVACPLClick(TObject *Sender);
        void __fastcall btnSSSK4_OLPBXClick(TObject *Sender);
        void __fastcall tmrPressurizarTimer(TObject *Sender);
        void __fastcall tmrDespressurizarTimer(TObject *Sender);
        void __fastcall btnPartirClick(TObject *Sender);
        void __fastcall btnPararClick(TObject *Sender);
        void __fastcall btnHabilita_EdicaoClick(TObject *Sender);
        void __fastcall btnEscorregClick(TObject *Sender);
        void __fastcall ListaTimer(TObject *Sender);
        void __fastcall btnResetClick(TObject *Sender);
        void __fastcall cmdInibirCmdClick(TObject *Sender);
        void __fastcall cmdInibirPressClick(TObject *Sender);
        void __fastcall btnSSSK1_TRAVARClick(TObject *Sender);
        void __fastcall btnSSSK2_TRAVARClick(TObject *Sender);
        void __fastcall btnSSSK3_TRAVARClick(TObject *Sender);
        void __fastcall btnSSSK4_TRAVARClick(TObject *Sender);
        void __fastcall btnSSSK1_FERRAMENTAClick(TObject *Sender);
        void __fastcall btnSSSK2_FERRAMENTAClick(TObject *Sender);
        void __fastcall btnHabilita_SSSClick(TObject *Sender);
        void __fastcall mnuBBELPNClick(TObject *Sender);
        void __fastcall mnuERClick(TObject *Sender);
        void __fastcall btnCtrlAutoTempClick(TObject *Sender);
        void __fastcall btnHabilita_PressClick(TObject *Sender);
        void __fastcall mnuStatusClick(TObject *Sender);
        void __fastcall mnuSSSMCPClick(TObject *Sender);
        void __fastcall mnuSSSTGClick(TObject *Sender);
        void __fastcall btnStatusClick(TObject *Sender);
        void __fastcall btnBBELPNClick(TObject *Sender);
        void __fastcall btnERClick(TObject *Sender);
        void __fastcall btnSSSMCPClick(TObject *Sender);
        void __fastcall btnSSSTGClick(TObject *Sender);
        void __fastcall btnMancaisClick(TObject *Sender);
        void __fastcall btnFecharClick(TObject *Sender);
private:	// User declarations
public:		// User declarations
        __fastcall TfrmPrincipal(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TfrmPrincipal *frmPrincipal;
//---------------------------------------------------------------------------
#endif
